import { Exam } from '../models/exam.model';

export const initialSampleExams = [
  {
    title: 'Full-Stack JavaScript & TypeScript Assessment',
    description: 'Mastery test on modern ES6+, TypeScript type system, Node.js event loop, and asynchronous programming.',
    category: 'Computer Science',
    teacherId: 'teacher_master_01',
    teacherName: 'Prof. Alex Mercer',
    teacherEmail: 'alex.mercer@testify.edu',
    accessType: 'free' as const,
    price: 0,
    durationMinutes: 30,
    totalMarks: 100,
    passMarks: 40,
    isPublished: true,
    totalEnrolled: 42,
    questions: [
      {
        id: 'q1',
        questionText: 'What is the output of typeof null in JavaScript?',
        options: ['"null"', '"undefined"', '"object"', '"number"'],
        correctOptionIndex: 2,
        marks: 20,
        explanation: 'In JavaScript, typeof null returns "object" due to a historical legacy bug.',
      },
      {
        id: 'q2',
        questionText: 'Which TypeScript keyword is used to create a type that represents the keys of another type?',
        options: ['keyof', 'typeof', 'instanceof', 'in'],
        correctOptionIndex: 0,
        marks: 20,
        explanation: 'The keyof operator in TypeScript takes an object type and produces a union of its keys.',
      },
      {
        id: 'q3',
        questionText: 'Which Node.js phase processes setImmediate() callbacks?',
        options: ['Timers Phase', 'Check Phase', 'Poll Phase', 'Close Callbacks'],
        correctOptionIndex: 1,
        marks: 20,
        explanation: 'The Check phase executes setImmediate() callbacks.',
      },
      {
        id: 'q4',
        questionText: 'What is the time complexity of searching an element in a balanced Binary Search Tree (BST)?',
        options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
        correctOptionIndex: 2,
        marks: 20,
        explanation: 'In a balanced BST, each step halves the remaining nodes, yielding O(log n).',
      },
      {
        id: 'q5',
        questionText: 'Which HTTP status code signifies "Forbidden / Access Denied"?',
        options: ['401', '403', '404', '500'],
        correctOptionIndex: 1,
        marks: 20,
        explanation: '403 Forbidden indicates that the server refuses to authorize the request.',
      },
    ],
  },
  {
    title: 'Data Structures & Algorithms Advanced Certification',
    description: 'Comprehensive evaluation covering Dynamic Programming, Graph Traversals (BFS/DFS), and Algorithmic Complexity.',
    category: 'Computer Science',
    teacherId: 'teacher_master_01',
    teacherName: 'Prof. Alex Mercer',
    teacherEmail: 'alex.mercer@testify.edu',
    accessType: 'paid' as const,
    price: 499,
    durationMinutes: 45,
    totalMarks: 100,
    passMarks: 50,
    isPublished: true,
    totalEnrolled: 28,
    questions: [
      {
        id: 'q1',
        questionText: 'Which data structure is fundamentally used for Breadth-First Search (BFS)?',
        options: ['Stack', 'Queue', 'Priority Queue', 'Binary Tree'],
        correctOptionIndex: 1,
        marks: 25,
        explanation: 'BFS uses a FIFO Queue to visit nodes level by level.',
      },
      {
        id: 'q2',
        questionText: 'What is the worst-case time complexity of QuickSort?',
        options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
        correctOptionIndex: 2,
        marks: 25,
        explanation: 'QuickSort degrades to O(n^2) when poor pivots are chosen.',
      },
      {
        id: 'q3',
        questionText: 'Dijkstra’s algorithm fails when the graph contains which of the following?',
        options: ['Cycles', 'Negative weight edges', 'Directed edges', 'Disjoint components'],
        correctOptionIndex: 1,
        marks: 25,
        explanation: 'Dijkstra assumes non-negative weights for its greedy path relaxation.',
      },
      {
        id: 'q4',
        questionText: 'Which paradigm does the 0/1 Knapsack problem typically employ for an optimal solution?',
        options: ['Greedy Approach', 'Divide and Conquer', 'Dynamic Programming', 'Backtracking only'],
        correctOptionIndex: 2,
        marks: 25,
        explanation: '0/1 Knapsack requires dynamic programming due to overlapping subproblems.',
      },
    ],
  },
  {
    title: 'Modern Web Architecture & React/Next.js Pro Examination',
    description: 'Test your understanding of React Server Components, hydration, SSR/SSG caching, and Next.js 14+ App Router.',
    category: 'Web Development',
    teacherId: 'teacher_web_02',
    teacherName: 'Dr. Sarah Jenkins',
    teacherEmail: 'sarah.jenkins@testify.edu',
    accessType: 'free' as const,
    price: 0,
    durationMinutes: 25,
    totalMarks: 100,
    passMarks: 40,
    isPublished: true,
    totalEnrolled: 64,
    questions: [
      {
        id: 'q1',
        questionText: 'In Next.js App Router, which directive marks a component to execute and render on the client side?',
        options: ['"use client"', '"use server"', '"use browser"', '"client only"'],
        correctOptionIndex: 0,
        marks: 25,
        explanation: '"use client" marks the boundary for client-side rendering and state in Next.js.',
      },
      {
        id: 'q2',
        questionText: 'What is the primary benefit of React Server Components (RSC)?',
        options: [
          'They increase client bundle size for faster rendering',
          'Zero client-side JavaScript bundle impact for server-only logic and direct DB access',
          'They replace client-side useState and useEffect entirely',
          'They only work in development mode',
        ],
        correctOptionIndex: 1,
        marks: 25,
        explanation: 'RSC delivers zero bundle size overhead to the client.',
      },
      {
        id: 'q3',
        questionText: 'Which React hook is designed for memoizing expensive calculation results?',
        options: ['useCallback', 'useMemo', 'useRef', 'useEffect'],
        correctOptionIndex: 2,
        marks: 25,
        explanation: 'useMemo caches computation results between re-renders.',
      },
      {
        id: 'q4',
        questionText: 'What is "Hydration" in the context of SSR?',
        options: [
          'Compiling CSS into Tailwind classes',
          'Attaching event listeners to server-rendered HTML in the browser',
          'Connecting to the MongoDB database',
          'Minifying images on the server',
        ],
        correctOptionIndex: 1,
        marks: 25,
        explanation: 'Hydration attaches interactivity and listeners to server-delivered static HTML.',
      },
    ],
  },
  {
    title: 'General Mathematics & Quantitative Aptitude Test',
    description: 'Analytical math examination covering probability, algebra, permutations, and geometric reasoning.',
    category: 'Mathematics',
    teacherId: 'teacher_math_03',
    teacherName: 'Prof. David Rahman',
    teacherEmail: 'david.rahman@testify.edu',
    accessType: 'free' as const,
    price: 0,
    durationMinutes: 30,
    totalMarks: 100,
    passMarks: 40,
    isPublished: true,
    totalEnrolled: 51,
    questions: [
      {
        id: 'q1',
        questionText: 'If a fair six-sided die is rolled twice, what is the probability of rolling a sum of 7?',
        options: ['1/6', '1/12', '7/36', '1/36'],
        correctOptionIndex: 0,
        marks: 25,
        explanation: '6 favorable outcomes out of 36 -> 6/36 = 1/6.',
      },
      {
        id: 'q2',
        questionText: 'Solve for x: 2^(2x + 1) = 32',
        options: ['x = 1', 'x = 2', 'x = 3', 'x = 4'],
        correctOptionIndex: 1,
        marks: 25,
        explanation: '32 = 2^5 => 2x + 1 = 5 => 2x = 4 => x = 2.',
      },
      {
        id: 'q3',
        questionText: 'What is the sum of the interior angles of a hexagon (6 sides)?',
        options: ['360°', '540°', '720°', '900°'],
        correctOptionIndex: 2,
        marks: 25,
        explanation: '(6 - 2) * 180° = 720°.',
      },
      {
        id: 'q4',
        questionText: 'In how many ways can 5 books be arranged on a shelf?',
        options: ['60', '120', '24', '720'],
        correctOptionIndex: 1,
        marks: 25,
        explanation: '5! = 120.',
      },
    ],
  },
];

export async function autoSeedDatabase(): Promise<void> {
  try {
    const count = await Exam.countDocuments();
    if (count === 0) {
      console.log('Database empty: auto-seeding sample exams...');
      await Exam.insertMany(initialSampleExams);
      console.log('Auto-seeded initial exams successfully.');
    }
  } catch (err) {
    console.warn('Auto-seed check non-critical warning:', err);
  }
}
